vault-dir = "/Users/nomura/Library/CloudStorage/Dropbox-Nakasuka_PJ/Nomura Shunichiro/capsula-vaults/otv-xlrm"

[pre-run]
contexts = [
    { type = "CwdContext" },
    { type = "CpuContext" },
    { type = "PlatformContext" },
    { type = "EnvVarContext", name = "PYTHONHASHSEED" },
    { type = "GitRepositoryContext", name = "pdag-examples", path = ".", path_relative_to_project_root = true },
    { type = "GitRepositoryContext", name = "pdag", path = "../capsula", path_relative_to_project_root = true },
    { type = "CommandContext", command = "git-push-check", cwd = ".", cwd_relative_to_project_root = true },
    { type = "CommandContext", command = "uv lock --locked", cwd = ".", cwd_relative_to_project_root = true },
    { type = "FileContext", path = "pyproject.toml", copy = true, path_relative_to_project_root = true },
    { type = "FileContext", path = "uv.lock", copy = true, path_relative_to_project_root = true },
]
reporters = [{ type = "JsonDumpReporter" }]

[in-run]
watchers = [{ type = "UncaughtExceptionWatcher" }, { type = "TimeWatcher" }]
reporters = [{ type = "JsonDumpReporter" }]

[post-run]
reporters = [{ type = "JsonDumpReporter" }]
